import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import { FileBarChart, Download, FileText, FileSpreadsheet } from 'lucide-react';
import PageHeader from '@/components/layout/PageHeader';
import Card from '@/components/common/Card';
import Button from '@/components/common/Button';
import Badge, { statusTone } from '@/components/common/Badge';
import Avatar from '@/components/common/Avatar';
import DataTable from '@/components/tables/DataTable';
import Modal from '@/components/common/Modal';
import Select from '@/components/common/Select';
import Input from '@/components/common/Input';
import { getReports, generateReport } from '@/services/reportService';
import { useAppDispatch } from '@/hooks/useAppDispatch';
import { setReports, addReport } from '@/redux/slices/reportSlice';
import { formatDate } from '@/utils/format';

export default function CeoReports() {
  const dispatch = useAppDispatch();
  const [reports, setLocal] = useState([]);
  const [loading, setLoading] = useState(true);
  const [genOpen, setGenOpen] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [form, setForm] = useState({ title: '', type: 'performance', period: '' });

  useEffect(() => {
    getReports().then((res) => { dispatch(setReports(res.data)); setLocal(res.data.items); setLoading(false); });
  }, [dispatch]);

  const generate = async () => {
    if (!form.title) { toast.error('Title is required'); return; }
    setGenerating(true);
    try {
      const res = await generateReport(form);
      dispatch(addReport(res.data));
      setLocal((prev) => [res.data, ...prev]);
      toast.success('Report generated');
      setGenOpen(false);
      setForm({ title: '', type: 'performance', period: '' });
    } catch { toast.error('Could not generate report'); }
    finally { setGenerating(false); }
  };

  const columns = [
    {
      key: 'title', label: 'Report', sortable: true,
      render: (r) => (
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-navy-100 dark:bg-navy-800">
            {r.format === 'XLSX' ? <FileSpreadsheet size={16} className="text-emerald-600" /> : <FileText size={16} className="text-navy-600 dark:text-navy-300" />}
          </div>
          <div><p className="font-medium text-navy-900 dark:text-gray-100">{r.title}</p><p className="text-xs text-gray-500">{r.type}</p></div>
        </div>
      ),
    },
    { key: 'period', label: 'Period', sortable: true },
    { key: 'generatedBy', label: 'Generated by', render: (r) => (
      <div className="flex items-center gap-2"><Avatar name={r.generatedBy} size="xs" /><span className="text-sm">{r.generatedBy}</span></div>
    ) },
    { key: 'format', label: 'Format', render: (r) => <Badge tone="navy">{r.format}</Badge> },
    { key: 'status', label: 'Status', render: (r) => <Badge tone={statusTone(r.status)} dot>{r.status}</Badge> },
    { key: 'generatedAt', label: 'Date', sortable: true, render: (r) => <span className="text-xs text-gray-500">{formatDate(r.generatedAt)}</span> },
    { key: 'actions', label: '', align: 'right', render: () => (
      <button className="rounded-md p-1.5 text-gray-400 hover:bg-gray-100 hover:text-navy-600 dark:hover:bg-navy-800" title="Download"><Download size={15} /></button>
    ) },
  ];

  return (
    <div>
      <PageHeader
        title="Reports"
        description="Generate, view, and download organization-wide reports."
        breadcrumbs={[{ label: 'Home', link: '/ceo/dashboard' }, { label: 'Reports' }]}
        actions={<Button size="sm" icon={FileBarChart} onClick={() => setGenOpen(true)}>Generate report</Button>}
      />

      <Card className="p-0">
        {loading ? (
          <div className="p-8 text-center text-sm text-gray-500">Loading reports…</div>
        ) : (
          <DataTable columns={columns} data={reports} />
        )}
      </Card>

      <Modal open={genOpen} onClose={() => setGenOpen(false)} title="Generate report" description="Create a new organization report." size="md"
        footer={<><Button variant="secondary" size="sm" onClick={() => setGenOpen(false)}>Cancel</Button><Button size="sm" loading={generating} onClick={generate}>Generate</Button></>}>
        <div className="space-y-4">
          <Input label="Report title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="e.g. Q3 2026 Performance" />
          <div className="grid gap-4 sm:grid-cols-2">
            <Select label="Type" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}
              options={[{ value: 'performance', label: 'Performance' }, { value: 'department', label: 'Department' }, { value: 'compliance', label: 'Compliance' }, { value: 'risk', label: 'Risk' }, { value: 'hr', label: 'HR' }]} />
            <Input label="Period" value={form.period} onChange={(e) => setForm({ ...form, period: e.target.value })} placeholder="e.g. Q3 2026" />
          </div>
        </div>
      </Modal>
    </div>
  );
}
